### ISSUE TITLE
Loading ng2-gridstack into Angular2 application generated with angular2-cli

### ISSUE THREAD

**Issue by jvecc** [ApolloSSC/ng2-gridstack#1]
Hi,

First of all, thank you for sharing this module ! 👍 
I am trying to use gridstack into an angular2 app. I must say that I am quite new to angular2, and I am facing the issue of being able to load ng2-gridstack into my app.
I get this : `ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-gridstack'`

By any chance, do you have an idea on how to use it with angular-cli ? 

Thank you !

**Comment by gperouffe** [comment]
Hi,

Can we have some more information about the structure of your project? How did you import ng2-gridstack? If you didn't use SystemJS, you may try :
```javascript
import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/ng2-gridstack'
```
Good luck!
