### ISSUE TITLE
Uncaught Error: Unexpected value 'GridStackComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by LeviBarker** [ApolloSSC/ng2-gridstack#10]
### Issue:
![https://img.shields.io/badge/using-angular--cli-red.svg](https://img.shields.io/badge/using-angular--cli-red.svg)
I am fairly new to Angular 2+ and am having a bit of trouble with the following error: 
> Uncaught Error: Unexpected value 'GridStackComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

My ```app.module.ts``` has this import statement, with each respectively included in my declarations.

    import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/';
    // I have also tried
    import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/ng2-gridstack';

I also have the required _.js_ files included in ```.angular-cli.json```

```
 "scripts": [
        "../node_modules/lodash/lodash.js",
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/gridstack/dist/gridstack.js"
      ],
```

I assume the error is coming from the fact that it's a declaration file, but I don't have the Angular2/Typescript knowledge to know how to fix this error.

Thanks for any help.

**Comment by markiodev** [comment]
I am also having this problem.

**Comment by devfcr** [comment]
me too :-(

**Comment by advorzhak** [comment]
I have same problem when I want to build my project for production.

**Comment by sinsunsan** [comment]
I have the same problem with a standard angular CLI install 

I have made the test to insert the component and the directive as a copy in my app it works 
https://github.com/sinsunsan/test-gridstack/tree/master/src/app

So it is probably an ES6 module import problem, but do not  know  which.

**Comment by gperouffe** [comment]
I tried to tackle all those import issues in the last release. You now only have to import GridStackModule and gridstack's css (see updated documentation). Let me know if there are other problems. I'm closing that for now.
