### ISSUE TITLE
module import error (documentation udpated needed)

### ISSUE THREAD

**Issue by sinsunsan** [ApolloSSC/ng2-gridstack#11]
In the readme you tell to put this line
`import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack'`

But for me it fail, for module import reason 
I need to added this line. 
import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/ng2-gridstack.js';

I do not know exactly  why it failed first. 

I tested that with a standard angular CLI install, so the bug is standard I think.

**Comment by gperouffe** [comment]
I tried to tackle all those import issues in the last release. You now only have to import GridStackModule and gridstack's css (see updated documentation). Let me know if there are other problems. I'm closing that for now.
