### ISSUE TITLE
Error: moduleId should be a string in 'GridStackComponent'

### ISSUE THREAD

**Issue by deanproxy** [ApolloSSC/ng2-gridstack#2]
This is the error I'm getting when I try to use ng2-gridstack in my project.  The error appears when rendering inside of developer tools.  This is using the latest Chrome browser.  The error looks like this:

    compiler.es5.js:14661 Uncaught Error: moduleId should be a string in "GridStackComponent". See 
    https://goo.gl/wIDDiL for more information.
    If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
        at syntaxError (http://localhost:4200/vendor.bundle.js:85057:34) [<root>]
        at componentModuleUrl (http://localhost:4200/vendor.bundle.js:98215:15) [<root>]
        at CompileMetadataResolver._loadDirectiveMetadata 
    (http://localhost:4200/vendor.bundle.js:97281:28) [<root>]
        at http://localhost:4200/vendor.bundle.js:97471:54 [<root>]
        at Array.forEach (native) [<root>]
        at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata 
    (http://localhost:4200/vendor.bundle.js:97470:41) [<root>]
        at http://localhost:4200/vendor.bundle.js:108638:58 [<root>]
        at Array.forEach (native) [<root>]
        at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:108637:43) [<root>]
        at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:108591:52) 
    [<root>]
        at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:108553:21) [<root>]
        at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:9615:25) 
    [<root>]
        at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:9601:21) [<root>]
        at Object.413 (http://localhost:4200/main.bundle.js:1774:124) [<root>]

My setup looks like this:

## app.module.ts
    
    import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/ng2-gridstack';
    ...
    @NgModule({
        declarations: [
            GridStackComponent,
            GridStackItemDirective
        ]
    });

## myfile.html
    
    <gridStack w="12" animate="true">
        <div gridStackItem [w]="itemWidth" [h]="itemHeight" [x]="itemX" [y]="itemY">
            <h1>Hello</h1>
        </div>
    </gridStack>

**Comment by gperouffe** [comment]
Hi, I have uploaded a new version to npm (0.1.11), would you try and tell me if you got it working?

**Comment by deanproxy** [comment]
@gperouffe That gets rid of the moduleId problem.  Now I have another problem, which is gridstack related, not necessarily your package issue.  `.gridstack is not a function`.   It appears as if the jQuery UI isn't being imported properly with Angular v2-4 when it's included by angular cli.  This causes gridstack to not initialize properly. I'm curious how others are getting gridstack to work given this issue...

**Comment by gperouffe** [comment]
@deanproxy Have you tried adding the libraries directly to your \<head\>? Like so:
```html
<link href="/path/to/gridstack.css" rel="stylesheet">
<link href="/path/to/gridstack-extra.css" rel="stylesheet">
<script src="/path/to/jquery-3.1.1.js"></script>
<script src="/path/to/jquery-ui-1.12.1.js"></script>
<script src="/path/to/jquery.ui.touch-punch.js"></script>
<script src="/path/to/lodash.js"></script>
<script src="/path/to/gridstack.js"></script>
```
Tip : jquery.ui.touch-punch allows you to use your gridstack on touchscreens.
