### ISSUE TITLE
gridstack with latest angular-cli 

### ISSUE THREAD

**Issue by lschaffer** [ApolloSSC/ng2-gridstack#5]
Hi
I have created a minimal ng project and installed the ng2-gridstack as you described 

app.module - 
import { GridStackComponent, GridStackItemDirective } from 'ng2-gridstack/ng2-gridstack';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    GridStackComponent,
    GridStackItemDirective,
    AppComponent
  ],
...
app.component.html -
<gridStack w="12" animate="true" 
	buttonClass="btn btn-default" 
	allowEditing="true" 
	[options]="gridstackOptions"
	[items]="panel.Cards" 
	(addFunction)="addCard()" 
	(saveFunction)="save($event)" 
	(deleteFunction)="deletePanel()" 
	(deleteCardFunc)="deleteCard($event)">
</gridStack>

then ng serve (compile, run without any error)

but in the browser I got this error

**zone.js:569 Unhandled Promise rejection: Failed to load gridstack.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load gridstack.component.html undefined
consoleError @ zone.js:569
handleUnhandledRejection @ zone.js:574
_loop_1 @ zone.js:609
drainMicroTaskQueue @ zone.js:613
ZoneTask.invoke @ zone.js:464
zone.js:571 Error: Uncaught (in promise): Failed to load gridstack.component.html
    at resolvePromise (zone.js:712) [<root>]
    at resolvePromise (zone.js:683) [<root>]
    at :4200/polyfills.bundle.js:3393:17 [<root>]
    at Zone.runTask (zone.js:165) [<root> => <root>]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (zone.js:464) [<root>]**

What should I change ?
Thx
Schaffer

**Comment by gperouffe** [comment]
I have uploaded ver. 0.1.13 to npm, would you tell me if it fixes your issue?

**Comment by lschaffer** [comment]
Hi 
The result is the same. I have uploaded this minimal cli project without node-deps maybe help you

[ng2-gridstack-demo.zip](https://github.com/ApolloSSC/ng2-gridstack/files/941460/ng2-gridstack-demo.zip)

**Comment by gperouffe** [comment]
I think you made a little mistake. You just uploaded the ng2-gridstack package itself.

**Comment by lschaffer** [comment]
Yes, this is the demo 
[gridstack-demo.zip](https://github.com/ApolloSSC/ng2-gridstack/files/941525/gridstack-demo.zip)

**Comment by lschaffer** [comment]
You can remove the gridstack.component.html from app, I have just copied it to test

**Comment by gperouffe** [comment]
I have made a little modification, please try ver. 0.1.14. And also, you should try to set "module": "commonjs" in your tsconfig.json.

**Comment by lschaffer** [comment]
No, the same error (commonjs includedd in tsconfig )
[gridstack-demo.zip](https://github.com/ApolloSSC/ng2-gridstack/files/941615/gridstack-demo.zip)

**Comment by gperouffe** [comment]
I will look deeper into it and get back to you later. Thanks for raising this issue

**Comment by gperouffe** [comment]
Hi, does 0.1.15 solves your issue?

**Comment by lschaffer** [comment]
Hi not really
Now the error is being dropped by compile (ng serve)

**Comment by lschaffer** [comment]
ERROR in ./~/ng2-gridstack/src/gridstack.component.js
Module not found: Error: Can't resolve './gridstack.component.html' in 'C:\temp\gridstack-demo\node_modules\ng2-gridstack\src'
 @ ./~/ng2-gridstack/src/gridstack.component.js 12:0-37
 @ ./~/ng2-gridstack/ng2-gridstack.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by gperouffe** [comment]
Try 0.1.16 There shouldn't be any reference to this html file anymore.

**Comment by lschaffer** [comment]
Another error
ncaught Error: Template parse errors:
Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
        (dblclick) = "onItemClick()" >
        </div>
    [ERROR ->]</div>"): ng:///AppModule/GridStackComponent.html@17:4
    at syntaxError (http://localhost:4200/vendor.bundle.js:29377:34) [<root

**Comment by gperouffe** [comment]
Ok, I took the time to bugfix this thing properly. I suggest you take a look at 0.2.0.

**Comment by lschaffer** [comment]
Now it starts but after using this template

**Comment by lschaffer** [comment]
<gridStack w="12" animate="true">
    <div gridStackItem
		[x]="0" [y]="0" [h]="3" [w]="3" [customid]="10">
		<h1>Hello 2</h1>
	</div>

</gridStack>

ERROR ReferenceError: $ is not defined
    at GridStackItemDirective.ngAfterViewInit (http://localhost:4200/vendor.bundle.js:63698:22)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:11819:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:11794:13)
    at callLifecycleHooksChildrenFirst (http://localhost:4200/vendor.bundle.js:11778:17)
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:12800:5)
    at callViewAction (http://localhost:4200/vendor.bundle.js:13107:17)
    at execComponentViewsAction (http://localhost:4200/vendor.bundle.js:13053:13)
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:12798:5)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13780:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:4200/vendor.bundle.js:13320:12)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:10889:63)
    at http://localhost:4200/vendor.bundle.js:5819:63
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:4200/vendor.bundle.js:5819:25)
    at ApplicationRef_._loadComponent (http://localhost:4200/vendor.bundle.js:5795:14)

**Comment by lschaffer** [comment]
template >

**Comment by lschaffer** [comment]
<gridStack w="12" animate="true">
    <div gridStackItem
		[x]="0" [y]="0" [h]="3" [w]="3" [customid]="10">
		<h1>Hello 2</h1>
	</div>

</gridStack>

**Comment by lschaffer** [comment]
`<gridStack w="12" animate="true">
    <div gridStackItem
		[x]="0" [y]="0" [h]="3" [w]="3" [customid]="10">
		<h1>Hello 2</h1>
	</div>

</gridStack>`

**Comment by lschaffer** [comment]
can you create and test a minimal demo angular-cli project (ng new)  ?

**Comment by gperouffe** [comment]
ERROR ReferenceError: $ is not defined 

This may mean that you didn't include jquery properly to your project. 0.2.0 works with my project, but I am not familiar with angular-cli, I may not be able to help you with this.

**Comment by lschaffer** [comment]
Hi it is very easy  ... ng new yourproject

**Comment by lschaffer** [comment]
then add your styles ,custom javascripts into .angular-cli.json // see the project what I have sent yesterday

**Comment by gperouffe** [comment]
I just had a look at your project, I do not have time to do more right now. You have to import gridstack.js dependencies as specified on their website.

In your index.html:
```html
<script src="path/to/jquery/3.1.1/jquery.min.js"></script>
<script src="path/to/jqueryui/1.11.2/jquery-ui.js"></script>
<script src="path/to/lodash.js/3.5.0/lodash.min.js"></script>
<script src="path/to/gridstack.js/0.2.6/gridstack.js"></script>

<link rel="stylesheet" href="path/to/gridstack.js/0.2.6/gridstack.css">
<link rel="stylesheet" href="path/to/ui/1.11.2/themes/smoothness/jquery-ui.css">
```

**Comment by gperouffe** [comment]
I close this issue as your current problem is not related.
