### ISSUE TITLE
Fetching error.

### ISSUE THREAD

**Issue by pratikpanchal4472** [ApolloSSC/ng2-gridstack#6]
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-gridstack' in 'C:\Users\admin\IdeaProjects\dummy\ui\src\app'
 @ ./src/app/app.module.ts 16:0-75
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

Getting Error while including in the project. checked the node_modules folder and found out that the ng2-gridstack.ts file is not being fetched while we do npm install.

**Comment by gperouffe** [comment]
You should not need ng2-gridstack.ts, try importing 'ng2-gridstack/ng2-gridstack'.

**Comment by pratikpanchal4472** [comment]
Any idea, how i can get rid of the buttons above the grid stack when I render.

**Comment by gperouffe** [comment]
I've added some toggles to these buttons in 0.2.1. See the updated documentation

* *addButtonText* (optional) : If present, will display a button that triggers addFunction.
* *saveButtonText* (optional) : If present, will display a button that triggers saveFunction.
* *deleteButtonText* (optional) : If present, will display a button that triggers deleteFunction.
* *deleteCardButtonText* (optional) : If present, will display a button that triggers deleteCardFunc.

**Comment by pratikpanchal4472** [comment]
Thanks for this. It is working as per my expectation. 

One more thing I needed is that, I'm using the component in my TS file and there are certain methods I am invoking on the elements (buttons/links) to reference to TS method but it is not working. 

`<gridStack w="12" animate="true" [options]="gridOptions"><div gridStackItem [x]="stack.gridRule?.xPlace" [y]="stack.gridRule?.yPlace" [h]="stack.gridRule?.height" 
        [w]="stack.gridRule?.width" [customid]="stack?.gridRuleId" *ngFor="let stack of gridStackData">
        <button md-raised-button (click)="onClickConfigure(stack)">
                Hello</button></div></gridStack>`

Here in this case, gridStackData is referring to my component but the event onClickConfigure(stack) is not referring to my component.
Any idea, why?

**Comment by gperouffe** [comment]
What is inside \<gridstack\> tags will be copied inside the gridstack component template via ng-content, thus not referring to your own component anymore. To use your own buttons, you have to put them out of the \<gridstack\> tags.

**Comment by gperouffe** [comment]
This should acomplish what you are trying:
```html
<ng-container *ngFor="let stack of gridStackData">
    <button md-raised-button (click)="onClickConfigure(stack)"> Hello</button>
    <gridStack w="12" animate="true" [options]="gridOptions"><div gridStackItem 
    [x]="stack.gridRule?.xPlace" [y]="stack.gridRule?.yPlace" [h]="stack.gridRule?.height" 
    [w]="stack.gridRule?.width" [customid]="stack?.gridRuleId"> </div>
    </gridStack>
<ng-container>
```

**Comment by gperouffe** [comment]
On second thought, what you are trying to achieve might not be possible, I did not understand that your were trying to handle events inside grid items.

**Comment by pratikpanchal4472** [comment]
I am trying to put the chart widget inside the grid and on chart click i should refer to native method. Is it anyway possible?

**Comment by gperouffe** [comment]
I think you would have to make a specific component and put it inside of each item. But I don't see any way you could call a method of the grid container component.
