### ISSUE TITLE
Update for Angular 4

### ISSUE THREAD

**Issue by NicoGit** [ApolloSSC/ng2-gridstack#8]
I get the following error when trying to use ng2-gridstack with angular 4 :+1: 

@angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed

Is it possible to update the plugin in order for it be compatible with angular v4 and use zone.js 0.8.x

**Comment by gperouffe** [comment]
The last release should be compatible with angular 4+, even if there are warnings upon installation regarding peer dependencies. See updated documentation to know how to import the library. Let me know if there are other problems. I'm closing that for now.
